spring:
  application:
    name: report.listener
  profiles:
    active: default
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_HOST:localhost}
      port: 27017
      username: sa
      password: sa
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${BROKER_URL:localhost:9092}
      function:
        bindings:
          consumerReport-in-0: # consumerReport-out -> consumerReport <- consumerReport-in
            destination: consumerReport
server:
  port: 7071
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
