spring:
  application:
    name: config.server
  profiles:
    active: develop
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pgimenez96/spring-cloud-lab.configs.git
          username: ${GIT_ACCESS_USER}
          password: ${GIT_ACCESS_TOKEN}
          default-label: main
          clone-on-start: true

server:
  port: 7777

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}