spring:
  application:
    name: companies-crud
  datasource:
    companies-db-postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/companies
      username: debuggeandoideas
      password: udemy
      driver-class-name: org.postgresql.Driver
      hikari:
        connection-timeout: 20000
        maximum-pool-size: 5
server:
  port: 8081
  servlet:
    context-path: /companies

log:
  level: DEBUG

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
