version: v1
spring:
  application:
    name: companies
  main:
    web-application-type: SERVLET
  profiles:
    active: develop
  datasource:
    companies-db-postgres:
      driver-class-name: org.postgresql.Driver
      connection-test-query: SELECT 1
      connection-init-sql: SELECT 1
      pool-name: companiesDbPostgresPool
      hikari:
        connection-timeout: 20000
        maximum-pool-size: 5
server:
  servlet:
    context-path: /@project.artifactId@
springdoc:
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
    url: /v3/api-docs
management:
  endpoints:
    web.response.include: health, info, metrics, prometheus, caches, circuitbreakers, circuitbreakerevents
    endpoint.health.show-details: always
  metrics:
    tags:
      application: '@project.artifactId@'
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    home-page-url-path: ${server.servlet.context-path}/
---
spring:
  config:
    activate:
      on-profile: develop
    import: "optional:configserver:http://localhost:7777"
  datasource:
    companies-db-postgres:
      jdbc-url: ${companies-db-postgres.jdbc-url}
      username: ${companies-db-postgres.username}
      password: ${companies-db-postgres.password}
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: circuitbreaker
server:
  port: 0
log:
  level: DEBUG
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: release
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  datasource:
    companies-db-postgres:
      jdbc-url: ${companies-db-postgres.jdbc-url}
      username: ${companies-db-postgres.username}
      password: ${companies-db-postgres.password}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}