spring:
  application:
    name: report.ms
  profiles:
    active: default
  config:
    import: "optional:configserver:http://localhost:7777"
server:
  servlet:
    context-path: /@project.artifactId@
  port: 7070
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    home-page-url-path: ${server.servlet.context-path}/
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/