spring:
  application:
    name: report.ms
  profiles:
    active: release
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:7777}"
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${BROKER_URL:localhost:9092}
      function:
        bindings:
          consumerReport-out-0: # consumerReport-out -> consumerReport <- consumerReport-in
            destination: consumerReport
server:
  servlet:
    context-path: /@project.artifactId@
  port: 7070
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    home-page-url-path: ${server.servlet.context-path}/
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
